### ISSUE TITLE
Différence avec ouvre-boite ?

### ISSUE THREAD

**Issue by l-vincent-l** [alphoenix/acces-information#6]
Salut,
Super projet, ça fait plaisir de voir des journalistes contribuer sur github et s'intéresser à la donnée publique. Mais quand je le vois, je ne peux m'empêcher de penser à [ouvre-boite](https://wiki.ouvre-boite.org/index.php?title=Accueil). Quelle est la différence principale ?

**Comment by alphoenix** [comment]
Bonjour ! C'est une idée que je porte depuis quelques mois maintenant et j'avais essayé [de lancer une discussion](https://twitter.com/alphoenix/status/775748582460784640) à ce sujet en septembre, sans recevoir beaucoup de réponses. J'ai depuis rencontré quelques journalistes qui se disent qu'il faut améliorer la pédagogie sur l'accès aux informations. Par ailleurs, je n'ai pas réussi à avoir des détails sur Ouvre-boîte et n'ai pas vu [le site](https://wiki.ouvre-boite.org/index.php?title=Accueil) avant ce message, malgré une tentative de prise de contact.
Je pense que ce sont des démarches qui peuvent être complémentaires.

**Comment by l-vincent-l** [comment]
Je pense aussi que les démarches sont complémentaires, le message était plus pour signaler l'existence d'un autre outil similaire.
